### PR TITLE
Fixed increment signedness

### LINKED ISSUE #6: Verification bug: Signed integer is casted to unsigned
When specifying a window in `totp_verifyi` a negative integer will be casted to an unsigned `size_t` in this line:
https://github.com/tilkinsc/COTP/blob/master/cotp.c#L233
This causes any window!=0 not to be working correctly. 

Another issue i had when trying to specify a window was that there is not much documentation for that parameter. Only by reading the sourcecode myself i found out that this parameter is in seconds.  I think a lot of the `totp_comparei` calls could be avoided when checking for the interval inside `OTPData`, so e.g. with an interval of 30s we would only need 1 call for a window of 30

### PR DESCRIPTION
**Pull request by feliwir**
Closes #6

### CODE REVIEW

**Comment by tilkinsc** [comment]
If you want to take this a step further, please convert the ints to longs.

**Comment by feliwir** [comment]
I was going for `int` since the `valid_window` can only be specified as `int` aswell. Should i change that parameter type aswell?

**Comment by tilkinsc** [comment]
Yeah of course. Converting to longs will ensure at least 32 bits are available which is what we intend.

**Comment by feliwir** [comment]
Switched all signatures to long

**Comment by tilkinsc** [comment]
Good work.

**Pull request merged**
