### PR TITLE
Makefile script

### LINKED ISSUE #17: We need a makefile or cmake build script

### PR DESCRIPTION
**Pull request by GruelingPine185**
Problem: Makefile needed
Solution: I made a Makefile... (couldn't be said simpler)

This PR includes the following:
- Dynamic library creation
- Static library creation
- Test file compilation for both C and C++
- All in a fairly simple and organized manner within a Makefile.

Please excuse the unaligned backslashes. On my system they are all aligned.

- Closes #17

### CODE REVIEW

**Comment by tilkinsc** [comment]
Github uses 8 space tabs just to make their users angry and use spaces. I will review this, but it most likely will end in having the generated code shifting away from a git submodule (for sanity reasons) and be baked in the makefile.

**Comment by GruelingPine185** [comment]
Makefiles are also like python where whitespace matters too. Makefiles require hard tabs rather than the preferred space-expanded tabs.

I can rewrite the makefile so as not to use submodules or any external code if you'd like. That should have been my goto to be honest.

I have seen several ways in which people write their Makefiles such as:
- Doing the bare minimum (for example, doing what's been done in your batch file)
- Making recipes for explicitly every file (something akin to what the generated Makefiles from Cmake scripts do)
- And doing something like I did, which is more scalable. The downside to this method is that you won't be able to write the messages as you've done without some issues. And it is a few more lines of code.

There may be other ways people have written scripts, but for your purposes how would you like it to be written?

**Comment by tilkinsc** [comment]
Two targets, one being the library (static/dynamic), and tests. Where tests are also part of all. Basically what you already have. If you are open to removing the submodule I'll leave you to that.

**Comment by GruelingPine185** [comment]
Quick question: when making #21 I noticed a `test.bat` script under `test/`. I was wondering if you'd like a bash script to go with that or just add that to the makefile (if do anything for it at all)?

**Comment by tilkinsc** [comment]
> Quick question: when making #21 I noticed a `test.bat` script under `test/`. I was wondering if you'd like a bash script to go with that or just add that to the makefile (if do anything for it at all)?

Its just temporary so I can emit the logs so I can attempt to keep the C and CPP output example in sync :)

**Comment by tilkinsc** [comment]
Closed to focus on #21

**Pull request closed without merging**
