### PR TITLE
Add a CMake based project

### PR DESCRIPTION
**Pull request by feliwir**
- [x] Add CMake project files
- [x] Add CTest integration
- [x] Add code coverage generation 
I'll change the README to include the buildstats, once this is merged

### CODE REVIEW

**Comment by tilkinsc** [comment]
I will allow this PR under the condition that it doesn't modify the test I have set up at all, and to undo the spacing edits. There is a manor of consistency I will keep for the other OTP projects. Please undo the referred changes.

**Comment by feliwir** [comment]
I undid the spacing changes

**Comment by tilkinsc** [comment]
Push your charges to the cmake branch when ready.

**Comment by feliwir** [comment]
Good call, i pushed on the master branch by accident - should be fixed now

**Comment by tilkinsc** [comment]
The tests are still deleted in test folder. Press Files Changed.

**Comment by feliwir** [comment]
They're not deleted for me - the only things deleted were some window specific scripts and precompiled binaries. The tests are executed by https://cmake.org/cmake/help/latest/manual/ctest.1.html now.

**Comment by tilkinsc** [comment]
"I will allow this PR under the condition that it doesn't modify the test I have set up at all"

image

**Comment by tilkinsc** [comment]
Closed due to age and inactivity.

**Pull request closed without merging**
